#!/bin/bash

# Add RPM Fusion
function add_rpmfusion() {
	echo_message header "Starting 'add_rpmfusion' function"
	# Check if valid RPM Fusion repository
	if [[ "$1" = "free" ]] || [[ "$1" = "nonfree" ]] ; then
		# Check if already present
		if [ -e /etc/yum.repos.d/rpmfusion-$1.repo ]; then
			echo_message info "RPM Fusion (${1^}) repository already added."
			whiptail --msgbox "The RPM Fusion (${1^}) repository is already added." 8 56
			$2
		else
			# Add repository
			echo_message info "Downloading RPM Fusion repository package..."
			elevate_privilege "dnf install -y https://download1.rpmfusion.org/$1/fedora/rpmfusion-$1-release-$(rpm -E %fedora).noarch.rpm"
			# Finished
			echo_message success "RPM Fusion (${1^}) repository has been added."
			whiptail --title "Finished" --msgbox "RPM Fusion (${1^}) repository has been added." 8 56
			$2
		fi
	else
		# If there is an error
		echo_message error "Not a valid RPM Fusion repository. Aborting..."
		whiptail --msgbox "Not a valid RPM Fusion repository. Sorry, try again." --title "Oops" 8 56
		$2
	fi
}

# Add Flatpak Repo
function add_flatpak_repo() {
	echo_message header "Starting 'add_flatpak_repo' function"
	# Check
	check_flatpak_repo $1
	# If repo is added
	if [ $? = 0 ]; then
		echo_message info "Repository already added."
		whiptail --msgbox "The $1 repository is already added." 8 56
	else
		# Add repository
		echo_message info "Adding flatpak repository..."
		flatpak remote-add --if-not-exists $1 $2
		echo_message success "Repository added."
		whiptail --title "Finished" --msgbox "The '$1' repository has been added." 8 56
	fi
}

# Add Repositories
function add_repositories {
	echo_message header "Starting 'add_repositories' function"
	echo_message title "Starting additions of third-party repositories..."
	# Draw window
	REPOS=$(eval `resize` && whiptail \
		--notags \
		--title "Third-Party Repositories" \
		--menu "\nWhat third-party repositories would you like to add?" \
		--ok-button "Install" \
		--cancel-button "Go Back" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		"rpmfusion_free"		"RPM Fusion (Free)" \
		"rpmfusion_nonfree"		"RPM Fusion (Non-free)" \
		"flathub"				"FlatHub" \
		3>&1 1>&2 2>&3)
	# check exit status
	while [ $? -eq 0 ]; do
		case "${REPOS}" in
		# RPM Fusion Free
		rpmfusion_free)
			add_rpmfusion "free" add_repositories
		;;
		# RPM Fusion Non-free
		rpmfusion_nonfree)
			add_rpmfusion "nonfree" add_repositories
		;;
		# FlatHub
		flathub)
			REPONAME="flathub"
			REPO="https://dl.flathub.org/repo/flathub.flatpakrepo"
			add_flatpak_repo $REPONAME $REPO
			add_repositories
		;;
		# Go Back
		*)
			# Cancelled
			echo_message info "Addition of third-party repositories cancelled."
			main
		;;
		esac
	done
}