#!/bin/bash

#----- DECLARATIONS -----#

dir="$(dirname "$0")"

PURGED="$dir/data/purge.list"

# CLEANUP SYSTEM
function cleanup {
echo ''
show_info 'What would you like to do?'
echo ''
echo '1. Remove unused pre-installed packages?'
echo '2. Remove old kernel(s)?'
echo '3. Remove duplicate packages?'
echo '4. Clean package cache?'
echo 'r. Return?'
echo ''
show_info 'Enter your choice:' && read REPLY
case $REPLY in
# Remove Unused Pre-installed Packages
1)
    echo 'Removing unused pre-installed applications...'
    echo ''
    echo 'Current package list:'
    echo ''
    for package in $(cat $PURGED)
    do 
    echo $package
    done
    echo ''
    read -p 'Proceed? (Y)es, (N)o : ' REPLY
    echo ''
    case $REPLY in
    # Positive action
    [Yy]* )
        show_info 'Requires root privileges:'
        sudo dnf remove $(cat $PURGED)
        show_success 'Done.'
        cleanup
        ;;
    # Negative action
    [Nn]* )
        clear && cleanup
        ;;
    # Error
    * )
        clear && show_error '\aSorry, try again.'
        cleanup
        ;;
    esac
    ;;
# Remove Old Kernel
2)
    echo 'Removing old Kernel(s)...'
    show_info 'Requires root privileges:'
    sudo package-cleanup -y --oldkernels --count=1
    show_success 'Done.'
    cleanup
    ;;
# Remove Duplicate Packages
3)
    echo 'Removing duplicate packages...'
    show_info 'Requires root privileges:'
    sudo package-cleanup -y --cleandupes
    show_success 'Done.'
    cleanup
    ;;
# Clean Package Cache
4)
    echo 'Cleaning package cache...'
    show_info 'Requires root privileges:'
    sudo dnf clean packages
    sudo dnf clean headers
    show_success 'Done.'
    cleanup
    ;;
# Return
[Rr]*) 
    clear && main;;
# Invalid choice
* ) 
    clear && echo 'Not an option, try again.' && cleanup;;
esac
}