#!/bin/bash

dir="$(dirname "$0")"

PURGE="$dir/data/purge.list"

function unused {
	if (eval `resize` && whiptail \
		--title "Remove Pre-installed Applications" \
		--yesno "Current list of pre-installed applications to remove: \n\n$(cat $PURGE) \n\nAre you sure you want proceed?" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		--scrolltext ) then
		show_info 'Removing pre-installed applications...'
		show_warning 'Requires root privileges'
		# Feel free to change the contents of 'utilities.list' in the data folder to whatever suits your preference.
		sudo dnf remove -y $(cat $PURGE)
		# Done
		show_success 'Done.'
		whiptail --title "Finished" --msgbox "Installation complete." 8 78
		cleanup
	else
		cleanup
	fi
}

# Remove old kernels
function kernels {
	if (whiptail --title "Remove Outdated Kernels" --yesno "If you're not currently using the newest kernel installed on your system, the following may break it. \n\nAre you sure you want proceed?" 10 60) then
		show_info 'Removing outdated kernel(s)...'
		show_warning 'Requires root privileges'
		sudo dnf remove $(dnf repoquery --installonly --latest-limit -3 -q)
		show_success 'Done.'
		whiptail --title "Finished" --msgbox "Outdated kernels have been successfully removed." 8 78
		cleanup
	else
		cleanup
	fi
}

# Remove Orphaned Packages
function orphaned {
	show_info 'Removing orphaned packages...'
	show_warning 'Requires root privileges'
	sudo dnf autoremove -y
	show_success 'Done.'
	whiptail --title "Finished" --msgbox "Orphaned packages have been successfully removed." 8 78
	cleanup
}

# Remove Duplicate Packages
function duplicates {
	show_info 'Removing duplicate packages...'
	show_warning 'Requires root privileges'
	sudo dnf remove $(dnf repoquery --duplicated --latest-limit -1 -q)
	show_success 'Done.'
	whiptail --title "Finished" --msgbox "Orphaned packages have been successfully removed." 8 78
	cleanup
}


# Clean Cache
function cache {
	show_info 'Cleaning cached package data...'
	show_warning 'Requires root privileges'
	sudo dnf clean all
	show_success 'Done.'
	whiptail --title "Finished" --msgbox "Package cache has been cleaned." 8 78
	cleanup
}

# Cleanup System
function cleanup {
	eval `resize` 
	CLEANUP=$(whiptail \
		--notags \
		--title "System Cleanup" \
		--menu "\nWhat would you like to do?" \
		--cancel-button "Go Back" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		cache		'Clean cached package data' \
		orphaned	'Remove orphaned packages' \
		duplicates	'Remove duplicate packages' \
		unused		'Remove unused pre-installed packages' \
		kernels		'Remove old kernel(s)' \
		3>&1 1>&2 2>&3)
	 
	exitstatus=$?
	if [ $exitstatus = 0 ]; then
		$CLEANUP
	else
		main
	fi
}