#!/bin/bash
#
# Update the list of packages in 'data/codecs.list' to suit your preferences

# Install multimedia codecs
function codecs {
	echo_message title "Starting 'codecs' function"
	# Variables
	DESC="multimedia codecs"
	TITLE="Multimedia Codecs"
	LIST=$(dirname "$0")'/data/codecs.list'
	# Draw window
	if (eval `resize` && whiptail \
		--title "$TITLE" \
		--yesno "Current list of $DESC to install: \n\n$(cat $LIST) \n\nProceed with installation?" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		--scrolltext) then
		echo_message info 'Starting installation...'
		# Install loop
		for PACKAGE in $(cat $LIST); do
			# Check if package is installed
			check_packages $PACKAGE
			EXITSTATUS=$?
			# If package is not installed
			if [ $EXITSTATUS = 1 ]; then
				# Install package
				echo_message info "Package '$PACKAGE' is not installed. Installing..."
				# Admin privileges
				elevate_privilege "dnf install -y $PACKAGE"
				# Done
				echo_message success 'Done.'
			else
				# Show already installed message
				echo_message success "Package '$PACKAGE' is installed."
			fi
		done
		# Finished
		echo_message success 'Done.'
		whiptail --title "Finished" --msgbox "Installation of $DESC is complete." 8 78
		main
	else
		main
	fi
}