#!/bin/bash

# THIRD PARTY DRIVERS
function drivers {
echo ''
echo 'What would you like to install? '
echo ''
echo '1. Broadcom wireless drivers (kmod-wl).'
echo 'r. Return'
echo ''
read -p 'Enter your choice: ' REPLY
case $REPLY in
# Broadcom Wireless Drivers
1) 
    if [ -e /etc/yum.repos.d/rpmfusion-free.repo ] && [ -e /etc/yum.repos.d/rpmfusion-nonfree.repo ]; then
        echo ''
    else
        read -p "The driver requires the RPM Fusion repository. Add it? (Y)es, (N)o : " INPUT
        case $INPUT in
            [Yy]* ) 
                echo 'Adding RPM Fusion to repositories...'
                echo 'Requires root privileges:'
                su -c 'yum localinstall --nogpgcheck http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm'
                echo 'Done.'
                # Update system
                echo 'Performing system update...'
                sudo yum -y update
                echo 'Done'
                ;;
            [Nn]* ) echo 'Okay, aborting' && drivers;;
            * )
            clear && echo 'Sorry, try again.'
            drivers
            ;;
        esac
    fi
    echo 'Installing Broadcom wireless drivers...'
    if [ $(uname -i) = 'i386' ]; then
        sudo yum install -y kmod-wl.i386
    elif [ $(uname -i) = 'x86_64' ]; then
        sudo yum install -y kmod-wl.x86_64
    fi    
    echo 'Done.'
    drivers
    ;;
# Return
[Rr]*) 
    clear && main;;
# Invalid choice
* ) 
    clear && echo 'Not an option, try again.' && drivers;;
esac
}