#!/bin/bash

#----- DECLARATIONS -----#

dir="$(dirname "$0")"

FAVS="$dir/data/favourites.list"

# INSTALL APPLICATIONS
function favourites {
# Install Favourite Applications
echo ''
echo 'Installing selected favourite applications...'
echo ''
echo 'Current package list:'
echo ''
for package in $(cat $FAVS)
do
echo $package
done
echo ''
read -p 'Proceed? (Y)es, (N)o : ' REPLY
echo ''
case $REPLY in
# Positive action
[Yy]* ) 
    show_info 'Requires root privileges:'
    # Feel free to change the contents of 'favourites.list' in the data folder to whatever suits your preference.
    sudo dnf install -y $(cat $FAVS)
    show_success 'Done.'
    main
    ;;
# Negative action
[Nn]* )
    clear && main
    ;;
# Error
* )
    clear && show_error '\aSorry, try again.'
    favourites
    ;;
esac
}
