#!/bin/bash

dir="$(dirname "$0")"

FAVS="$dir/data/favs.list"

# Install preferred applications using the list of packages 'data/favs.list'
function favs {
	if (eval `resize` && whiptail \
		--title "Preferred Applications" \
		--yesno "Current list of preferred applications to install: \n\n$(cat $FAVS) \n\nProceed with installation?" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		--scrolltext) then
		show_info 'Installing...'
		show_warning 'Requires root privileges'
		# For loop for installing
		for PACKAGE in $(cat $FAVS)
		do
			# Check if package is installed
			PKGCHECK=$(dnf list installed | grep "$PACKAGE")
			if [ "" == "$PKGCHECK" ]; then
				show_info "Package '$PACKAGE' is not installed. Installing..."
				# Install package
				sudo dnf install -y $PACKAGE
				show_success 'Done.'
			else
				show_success "Package '$PACKAGE' is installed."
			fi
		done
		show_success 'Done.'
		whiptail --title "Finished" --msgbox "Installation of your preferred applications is complete." 8 78
		main
	else
		main
	fi
}