#!/bin/bash
#
# Update the list of packages in 'data/gnome-apps.list' to suit your preferences

# Install GNOME Core Apps
function gnome_apps {
	echo_message title "Starting 'gnome_apps' function..."
	# Check list
	LIST=$(dirname "$0")'/data/gnome-apps.list'
	# Draw window
	if (eval `resize` && whiptail \
		--title "GNOME Core Apps" \
		--yesno "Current list of GNOME core apps: \n\n$(for LINE in $(cat $LIST); do echo '  '$LINE; done) \n\nWould you like to install these apps?" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		--scrolltext ) then
		# Install loop
		echo_message info 'Installing GNOME core apps...'
		for PACKAGE in $(cat $LIST); do
			# Check if package is installed
			check_packages $PACKAGE
			EXITSTATUS=$?
			# If package is not installed
			if [ $EXITSTATUS = 1 ]; then
				# Install package
				echo_message info "'$PACKAGE' is not installed. Installing..."
				# Admin privileges
				elevate_privilege "dnf install -y $PACKAGE"
				# Done
				echo_message success "'$PACKAGE' installation is complete."
			else
				# Show already installed message
				echo_message success "Package '$PACKAGE' is installed."
			fi
		done
		# Finish
		echo_message success "Installation complete."
		whiptail --title "Finished" --msgbox "GNOME Core Apps installation is complete." 8 64
		main
	else
		main
	fi
}