#!/bin/bash

#----- DECLARATIONS -----#

EXTRAS="data/gnome-extras.list"

# INSTALL GNOME COMPONENTS
function gnome {
# Install extra GNOME components
echo 'Installing extra GNOME components...'
echo ''
echo 'Current package list:'
echo ''
for package in $(cat $EXTRAS)
do 
echo $package
done
echo ''
read -p 'Proceed? (Y)es, (N)o : ' REPLY
echo ''
case $REPLY in
# Positive action
[Yy]* )
    echo 'Requires root privileges:'
    # Feel free to change the contents of "gnome-extras.list" to whatever suits your preferences.
    sudo yum install -y $(cat $EXTRAS)
    echo 'Done.'
    main
    ;;
# Negative action
[Nn]* )
    clear && main
    ;;
# Error
* )
    clear && echo 'Sorry, try again.'
    gnome
    ;;
esac
}