#!/bin/bash#
#
# When adding (or removing) any functions remember to update
# the 'install_from_source' function below to reflect any changes you make

# Automatically import manual functions
function import_manual_functions {
	DIR="functions/manual"
	# iterate through the files in the 'functions/manual' folder
	for FUNCTION in $(dirname "$0")/$DIR/*; do
		if [[ -d $FUNCTION ]]; then
			continue
		elif [[ -f $FUNCTION ]]; then
			# source the function file
			. $FUNCTION
		fi
	done
}

# Install Software From Source
function install_from_source {
	NAME="Compiled Software"
	echo_message title "Starting installation of ${NAME,,}..."
	import_manual_functions
	# Draw window
	FROMSOURCE=$(eval `resize` && whiptail \
		--notags \
		--title "Install $NAME" \
		--menu "\nWhat ${NAME,,} would you like to install?" \
		--ok-button "Install" \
		--cancel-button "Go Back" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		'install_libfprint_git'		'libprintf (git)' \
		3>&1 1>&2 2>&3)

	# check exit status
	if [ $? = 0 ]; then
		echo_message header "Starting '$FROMSOURCE' function..."
		$FROMSOURCE
	else
		# Cancelled
		echo_message info "Installation of ${NAME,,} cancelled."
		main
	fi
}