#!/bin/bash

# Install OpenH264 Codecs
function openh264_codec {
	echo_message header "Starting 'openh264_codec' function"
	# Variables
	NAME="OpenH264 Codec"
	REPO="fedora-cisco-openh264"
	PACKAGE=gstreamer1-plugin-openh264
	# Check if package is installed
	if [ $(check_packages $PACKAGE; echo $?) = 1 ]; then
		echo_message warning "Package '$PACKAGE' is not installed. Installing..."
		# Add repository
		echo_message info "Enabling '$REPO' repository..."
		elevate_privilege "dnf config-manager --set-enabled $REPO"
		# Install package(s)
		echo_message info "Installing $NAME..."
		elevate_privilege "dnf install -y $PACKAGE"
		# Done
		echo_message success "Installation of '$PACKAGE' complete."
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 56
		install_codecs
	else
		# Already installed
		echo_message success "$NAME already installed."
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 56
		install_codecs
	fi
}

# Install FFmpeg Codecs
function ffpmeg_codecs {
	echo_message header "Starting 'ffpmeg_codecs' function"
	# Add RPM Fusion
	if (eval `resize` && whiptail \
		--title "Add RPM Fusion (free) Repository?" \
		--yesno "The RPM Fusion (free) repository is required for these codecs.\n\nProceed with installation?" \
		10 60) then
		# Add RPM Fusion Free
		add_rpmfusion free
	else
		install_codecs
	fi
	# Update the list of packages in 'data/codecs-ffmpeg.list' to suit your preferences
	install_from_list codecs-ffmpeg "FFmpeg multimedia codecs" install_codecs
}

# Install GStreamer (free) Codecs
function gstreamer_free {
	echo_message header "Starting 'gstreamer_free' function"
	# Update the list of packages in 'data/codecs-gstreamer-free.list' to suit your preferences
	install_from_list codecs-gstreamer-free "GStreamer (free) multimedia codecs" install_codecs
}

# Install GStreamer (non-free) Codecs
function gstreamer_nonfree {
	echo_message header "Starting 'gstreamer_nonfree' function"
	# Add RPM Fusion 
	if (eval `resize` && whiptail \
		--title "Add RPM Fusion (non-free) Repository?" \
		--yesno "The RPM Fusion (non-free) repository is required for these codecs.\n\nProceed with installation?" \
		10 60) then
		# Add RPM Fusion Non-free
		add_rpmfusion nonfree
	else
		install_codecs
	fi
	# Update the list of packages in 'data/codecs-gstreamer-nonfree.list' to suit your preferences
	install_from_list codecs-gstreamer-nonfree "GStreamer (non-free) multimedia codecs" install_codecs
}

# Install Codecs
function install_codecs {
	echo_message header "Starting 'install_codecs' function"
	NAME="Multimedia Codecs"
	echo_message title "Starting $NAME installation..."
	# Draw window
	CODECS=$(eval `resize` && whiptail \
		--notags \
		--title "Install $NAME" \
		--menu "\nWhich $NAME would you like to install?" \
		--ok-button "Install" \
		--cancel-button "Go Back" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		'gstreamer_free'	'GStreamer (free) Codecs' \
		'gstreamer_nonfree'	'GStreamer (non-free) Codecs' \
		'ffpmeg_codecs'		'FFmpeg Codecs' \
		'openh264_codec'	'OpenH264 Codec' \
		3>&1 1>&2 2>&3)
	# check exit status
	if [ $? = 0 ]; then
		$CODECS
	else
		# Cancelled
		echo_message info "$NAME installation cancelled."
		main
	fi
}