#!/bin/bash

# Install preferred apps
function install_favs {
	echo_message header "Starting 'install_favs' function..."
	# Update the list of packages in 'data/favs-apps.list' to suit your preferences
	install_from_list favs-apps "preferred applications" main
}

# Install preferred development tools
function install_dev {
	echo_message header "Starting 'install_dev' function..."
	# Update the list of packages in 'data/favs-dev.list' to suit your preferences
	install_from_list favs-dev "preferred development tools" main
}

# Install preferred utilities
function install_utils {
	echo_message header "Starting 'install_utils' function..."
	# Update the list of packages in 'data/favs-utils.list' to suit your preferences
	install_from_list favs-utils "preferred utilities" main
}

# Install from list
function install_from_list() {
	# echo_message header "Starting 'install_from_list' function..."
	echo_message title "Starting installation of ${2}..."
	# Variables
	LIST=$(dirname "$0")'/data/'${1}'.list'
	# Draw window
	if (eval `resize` && whiptail \
		--title "Install ${2^}" \
		--yesno "Current list of packages that will be installed: \n\n$(cat ${LIST}) \n\nWould you like to proceed?" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		--scrolltext \
		3>&1 1>&2 2>&3) then
		# Install loop
		for PACKAGE in $(cat $LIST); do
			# Check if package is installed
			if [ $(check_packages $PACKAGE; echo $?) = 1 ]; then
				# Install package
				echo_message warning "Package '$PACKAGE' is not installed. Installing..."
				# Admin privileges
				elevate_privilege "dnf install -y $PACKAGE"
				# Check if failed
				if [[ $? != 0 ]]; then
					echo_message error "Error installing '$PACKAGE'."
				fi
			else
				# Show already installed message
				echo_message info "Package '$PACKAGE' is installed."
			fi
		done
		# Finished
		echo_message success 'Installation complete.'
		whiptail --title "Finished" --msgbox "Installation of ${2} is complete." 8 56
		$3
	else
		# Cancelled
		echo_message info 'Installation cancelled.'
		$3
	fi
}