#!/bin/bash

# Add RPM Fusion
function add_rpmfusion() {
	# Variables
	REPONAME="RPM Fusion ($@)"
	VERSION="$@"
	if [[ "$VERSION" = "free" ]] || [[ "$VERSION" = "nonfree" ]] ; then
		# Check
		if [ -e /etc/yum.repos.d/rpmfusion-$VERSION.repo ]; then
			echo_message info 'Repository already added.'
			whiptail --msgbox "The $REPONAME repository is already added. Proceeding." 8 78
		else
			# Add repository
			echo_message info 'Adding repository...'
			elevate_privilege "dnf install https://download1.rpmfusion.org/$VERSION/fedora/rpmfusion-$VERSION-release-$(rpm -E %fedora).noarch.rpm"
			echo_message success 'Done.'
			whiptail --title "Finished" --msgbox "$REPONAME repository has been added." 8 78
		fi
	else
		echo_message error "Not a correct RPM Fusion repository. Aborting..."
		# Draw window
		whiptail --msgbox "Not a correct RPM Fusion repository. Sorry, try again." --title "Oops" 8 64
	fi
}

# Add Repositories
function repositories {
	eval `resize` 
	EXITSTATUS=$?
	if [ $EXITSTATUS = 0 ]; then
		status="0"
		while [ "$status" -eq 0 ]; do
			REPOS=$(whiptail \
				--title "Third-Party Repositories" \
				--radiolist \
				"Which third-party repositories would you like to add?"\
				--ok-button "Add" \
				--cancel-button "Go Back" \
				$LINES $COLUMNS $(( $LINES - 12 )) \
				"rpmfusion_free"		"RPM Fusion (Free)" ON \
				"rpmfusion_nonfree"		"RPM Fusion (Non-free)" OFF \
				3>&1 1>&2 2>&3)

			case "${REPOS}" in
			# RPM Fusion Free
			rpmfusion_free)
				add_rpmfusion free
				repositories
			;;
			# RPM Fusion Non-free
			rpmfusion_nonfree)
				add_rpmfusion nonfree
				repositories
			;;
			# Go Back
			*) status=1
				main
			;;
			esac
		done
	else
		main
	fi
}