#!/bin/bash

# Automatically set preferred gsettings keys as outlined in the 'gsettings.list' file
# 'gsettings' can be obtained by executing "dconf watch /" and then manually changing settings
function gsettings_config {
	echo_message info "Setting preferred application-specific & desktop settings..."
	# Variables
	LIST=$(dirname "$0")'/data/gsettings.list'
	while IFS= read line
	do
		gsettings set $line
	done < "$LIST"
	# Finished
	echo_message success "Settings changed successfully."
	whiptail --title "Finished" --msgbox "Settings changed successfully." 8 56
	system_configure
}


# Put SELinux in permissive mode
function selinux {
	# Check if SELinux is aleady in permissive mode.
	if [[ $(cat '/etc/selinux/config' | grep -q 'SELINUX=permissive'; echo $?) != 0 ]]; then
		echo_message info "Configuring SELinux to run in permissive mode..."
		superuser_do "sed --in-place s/SELINUX=.*$/SELINUX=permissive/g /etc/selinux/config"
		# Finished
		echo_message info "SELinux successfully set to permissive mode."
		whiptail --title "Finished" --msgbox "SELinux successfully set to permissive mode." 8 56
		system_configure
	else
		# Already configured
		echo_message info "SELinux is aleady in permissive mode."
		whiptail --title "Finished" --msgbox "SELinux is aleady in permissive mode." 8 56
		system_configure
	fi
}

# Add current user to sudo group (wheel)
function add_to_sudo {
	# Check if user is already in wheel
	if [[ $(groups $USER | grep -q 'wheel'; echo $?) != 0 ]]; then
		echo_message warning "This user account isn't in the wheel user group."
		if (whiptail --title "Change User Group" --yesno "Are you sure you want to proceed with modifying current user?" 10 60) then
			# Adding user to 'wheel' group.
			echo_message info "Adding user to 'wheel' group."
			superuser_do "usermod -a -G wheel $USER"
			# Finished
			echo_message success "User added to 'wheel' group."
			whiptail --title "Finished" --msgbox "User modification complete." 8 56
		else
			echo_message error "User cancelled action. Aborting..."
			# Draw window
			whiptail --msgbox "Current user not modified at this time." --title "Abort" 8 56
			system_configure
		fi
	else
		# Already configured
		echo_message info "User aleady in sudo group."
		whiptail --title "Finished" --msgbox "Current user aleady has sudo privileges." 8 56
		system_configure
	fi
}

# Enable Fedora Test Updates repository
function test_updates {
	echo_message info "Enabling Fedora Test Updates repository..."
	superuser_do "dnf --enablerepo=updates-testing check-update"
	# Finished
	echo_message success "Fedora Test Updates repository enabled."
	whiptail --title "Finished" --msgbox "Fedora Test Updates repository enabled." 8 56
	system_configure
}

# limit number of concurrently installed packages 
function limit_packages {
	# maximum number of packages
	MAX="5"
	LIMIT=$(whiptail \
		--inputbox \
		--title "Set Installed Package Limit" \
		"\nLimit the number of packages that will be concurrently installed by DNF. The minimal number of packages is 2 and a value of 1 is unlimited. \n\nPlease enter a number between 1 and $MAX (default = 3):\n" \
		14 72 3>&1 1>&2 2>&3)
	# check exit status
	if [ $? = 0 ]; then
		# check if input is a number
		if ! [[ "$LIMIT" =~ '^[0-9]+$' ]] && ! [ "$LIMIT" -ge 1 -a "$LIMIT" -le $MAX ] ; then
			echo_message error "Input was not a integer between 1 and $MAX. Aborting..."
			# Draw window
			whiptail --msgbox "Input was not a integer between 1 and $MAX. Sorry, try again." --title "Oops" 8 56
			limit_packages
		else
			# Change 'installonly_limit' in '/etc/dnf/dnf.conf' to limit packages
			echo_message info "Changing installonly_limit in DNF configuration file..."
			# Admin privileges
			superuser_do "sed --in-place s/installonly_limit=.*$/installonly_limit=${LIMIT}/g /etc/dnf/dnf.conf"
			# Finished
			echo_message success "Package limit changed successfully."
			whiptail --title "Finished" --msgbox "Package limit changed successfully." 8 56
			system_configure
		fi
	else
		system_configure
	fi
}

# Configure System
function system_configure {
	NAME="System Configuration"
	echo_message title "Starting ${NAME,,}..."
	# Draw window
	CONFIGURE=$(eval `resize` && whiptail \
		--notags \
		--title "$NAME" \
		--menu "\nWhat would you like to do?" \
		--cancel-button "Go Back" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		'gsettings_config'          'Set preferred application & desktop settings' \
		'test_updates'              'Enable Fedora Test Updates repository' \
		'limit_packages'            'Limit the number of concurrently installed packages' \
		'selinux'                   'Put SELinux in permissive mode' \
		'add_to_sudo'               'Add current user to sudoers group' \
		3>&1 1>&2 2>&3)
	# check exit status
	if [ $? = 0 ]; then
		echo_message header "Starting '$CONFIGURE' function"
		$CONFIGURE
	else
		# Cancelled
		echo_message info "$NAME cancelled."
		main
	fi
}