#!/bin/bash

# Perform system update
function system_update {
	NAME="System update"
	echo_message title "Performing system update..."
	# Check if there are updates
	if [[ "$(echo $(dnf check-update -q | wc -l ))" -gt 0 ]]; then
		# Draw window
		if (eval `resize` && whiptail \
			--title "${NAME^}" \
			--yesno "Current list of packages to be updated: \n\n$(dnf list -q --updates) \n\nAre you sure you want proceed?" \
			$LINES $COLUMNS $(( $LINES - 12 )) \
			--scrolltext ) then
			# Admin privileges
			elevate_privilege "dnf update -y"
			# Check if failed
			if [[ $? != 0 ]]; then
				echo_message info "Nothing to update."
				whiptail --title "Finished" --msgbox "Nothing to update." 8 56
				main
			fi
			# Finished
			echo_message success "$NAME complete."
			whiptail --title "Finished" --msgbox "$NAME complete." 8 56
			main
		else
			# Cancelled
			echo_message info "$NAME cancelled."
			main
		fi
	else
		# If no updates are available
		echo_message info "No updates available."
		whiptail --title "Finished" --msgbox "No updates are available." 8 56
		main
	fi
}
