#!/bin/bash

# Perform system update
function system_update {
	echo_message header "Starting 'system_update' function"
	echo_message title 'Performing system update...'
	# Draw window
	if (whiptail --title "System Update" --yesno "Proceed with system update?" 10 60) then
		# Admin privileges
		elevate_privilege "dnf upgrade -y"
		# Check if failed
		if [[ $? != 0 ]]; then
			echo_message info "Nothing to update."
			whiptail --title "Finished" --msgbox "Nothing to update." 8 64
		fi
		# Done
		echo_message success 'System update complete.'
		whiptail --title "Finished" --msgbox "System update complete." 8 64
	else
		# Cancelled
		echo_message info 'System update cancelled.'
		main
	fi
}