#!/bin/bash

# THIRD PARTY THEMES
function themes {
show_info 'What would you like to install? '
echo ''
echo '1. Moka Project themes'
echo 'r. Return'
echo ''
show_info 'Enter your choice :' && read REPLY
case $REPLY in
# Moka Icon Theme
1)
    # Add repository
    echo 'Adding Moka Icon Theme repository to sources...'
    show_info 'Requires root privileges:'
    sudo curl -o /etc/yum.repos.d/moka-stable.repo http://mokaproject.com/packages/rpm/moka-stable.repo
    # Update repository information
    echo 'Updating repository information...'
    show_info 'Requires root privileges:'
    sudo yum update
    # Install package(s)
    echo 'Installing Moka Project themes...'
    show_info 'Requires root privileges:'
    sudo dnf install faba-icon-theme
    sudo dnf install moka-icon-theme
    sudo dnf install orchis-gtk-theme
    show_success 'Done.'
    themes
    ;;
# Return
[Rr]*) 
    clear && customize;;
# Invalid choice
* ) 
    clear && show_error '\aNot an option, try again.' && themes;;
esac
}