#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/apps/dropbox
source $dir/functions/apps/chrome
source $dir/functions/apps/oracle-java
source $dir/functions/apps/rvm
source $dir/functions/apps/slack
source $dir/functions/apps/sublime-text

# Install Third-Party Applications
function thirdparty {
	eval `resize`
	THIRDPARTY=$(whiptail \
		--notags \
		--title "Third-Party Installation" \
		--menu "\nWhat third-party software would you like to install?" \
		--ok-button "Install" \
		--cancel-button "Go Back" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		'dropbox'		'Dropbox' \
		'chrome'		'Google Chrome' \
		'oracle-java'	'Oracle Java' \
		'rvm'			'Ruby Version Manager (RVM)' \
		'slack'			'Slack' \
		'sublime_text'	'Sublime Text 3' \
		3>&1 1>&2 2>&3)
	 
	exitstatus=$?
	if [ $exitstatus = 0 ]; then
		$THIRDPARTY
	else
		main
	fi
}

