#!/bin/bash

# Perform system upgrade
function update {
if (whiptail --title "System Update" --yesno "Proceed with system update?" 10 60) then
    # Distro-Sync
    show_info 'Performing system update...'
    sudo dnf distro-sync -y
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "System update complete." 8 78
    main
else
    clear && main
fi
}