#!/bin/bash

# Perform system update
function update {
	echo_message title "Starting 'update' function"
	# Draw window
	if (whiptail --title "System Update" --yesno "Proceed with system update?" 10 60) then
		# Update
		echo_message info 'Performing system update...'
		# Admin privileges
		elevate_privilege "dnf update -y"
		# Done
		echo_message success 'System update complete.'
		whiptail --title "Finished" --msgbox "System update complete." 8 64
	else
		main
	fi
}