#!/bin/bash

#----- DECLARATIONS -----#

dir="$(dirname "$0")"

# SYSTEM UPGRADE
function upgrade {
# Perform system upgrade
echo ''
show_info 'Proceed with system upgrade? (Y)es, (N)o : ' 
read REPLY
echo ''
case $REPLY in
# Positive action
[Yy]* )
    # Upgrading system
    echo 'Performing system upgrade...'
    show_info 'Requires root privileges:'
    sudo yum distro-sync -y
    show_success 'Done.'
    main
    ;;
# Negative action
[Nn]* )
    clear && main
    ;;
# Error
* )
    clear && show_error '\aSorry, try again.'
    upgrade
    ;;
esac
}