#!/bin/bash

dir="$(dirname "$0")"

UTILS="$dir/data/utilities.list"

# Install preferred utilities using the list of packages 'data/utilities.list'
function utilities {
	if (eval `resize` && whiptail \
		--title "Preferred System Utilities" \
		--yesno "Current list of preferred system utilities: \n\n$(cat $UTILS) \n\nProceed with installation?" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		--scrolltext) then
		show_info 'Installing...'
		show_warning 'Requires root privileges'
		# For loop for installing
		for PACKAGE in $(cat $UTILS)
		do
			# Check if package is installed
			PKGCHECK=$(dnf list installed | grep "$PACKAGE")
			if [ "" == "$PKGCHECK" ]; then
				show_info "Package '$PACKAGE' is not installed. Installing..."
				# Install package
				sudo dnf install -y $PACKAGE
				show_success 'Done.'
			else
				show_success "Package '$PACKAGE' is installed."
			fi
		done
		show_success 'Done.'
		whiptail --title "Finished" --msgbox "Installation of your preferred system utilities is complete." 8 78
		main
	else
		main
	fi
}