#!/bin/bash

# Install Chrome
function install_chrome { 
	# Variables
	REPO="https://dl.google.com/linux/direct"
	PACKAGE=google-chrome-$@
	NAME="Google Chrome ($@)"
	# Check if package is installed
	if [ $(check_packages $PACKAGE; echo $?) = 1 ]; then
		# Install package(s)
		echo_message info "$NAME is not installed. Downloading remote package..."
		# Download RPM file that matches system architecture
		case `uname -i` in
			i386|i486|i586|i686)
				whiptail --title  "No 32-bit packages are available to download." --msgbox "Error." 8 78
				thirdparty
				;;
			x86_64)
				elevate_privilege "dnf --nogpgcheck install -y ${REPO}/${PACKAGE}_current_x86_64.rpm"
				;;
			*)
				whiptail --title "Error." --msgbox "No packages available to download." 8 64
				;;
		esac
		# Cleanup and finish
		rm $PACKAGE*.rpm
		# Done
		echo_message success "Installation of '$PACKAGE' complete."
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 64
		status=1
		thirdparty
	else
		# Already installed
		echo_message info "$NAME already installed."
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 64
		thirdparty
	fi
}

# Google Chrome
function chrome {
	EXITSTATUS="0"
	while [ "$EXITSTATUS" -eq 0 ]; do
		VERSION=$(eval `resize` && whiptail \
		--title "Google Chrome" \
		--radiolist "Which version of Chrome would you like to install?" \
		--ok-button "Install" \
		--cancel-button "Go Back" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		"stable"	"Stable build" ON \
		"beta"		"Beta build" OFF \
		"unstable"	"Unstable build" OFF \
		3>&1 1>&2 2>&3) 
		# Change to lower case and remove spaces.
		case "${VERSION}" in
			stable)
				install_chrome stable
				EXITSTATUS=1
			;;
			beta)
				install_chrome beta
				EXITSTATUS=1
			;;
			unstable)
				install_chrome unstable
				EXITSTATUS=1
			;;
			*)
				EXITSTATUS=1
				thirdparty
			;;
		esac
	done
}