#!/bin/bash

# Dropbox
function dropbox {
	# Variables
	PACKAGE=nautilus-dropbox
	VERSION="2015.10.28-1.fedora"
	REPO="https://linux.dropbox.com/packages/fedora"
	NAME="Dropbox"
	# Install
	echo_message header "Begin $NAME installation"
	# Check if package is installed
	if [ $(check_packages $PACKAGE; echo $?) = 1 ]; then
		# Install package(s)
		echo_message info "$NAME is not installed. Downloading remote package..."
		# Download RPM file that matches system architecture
		case `uname -i` in
			i386|i486|i586|i686)
				# Install remote package
				echo_message warning "Requires root privileges"
				elevate_privilege "dnf --nogpgcheck install -y ${REPO}/${PACKAGE}-${VERSION}.i386.rpm"
				;;
			x86_64)
				# Install remote package
				echo_message warning "Requires root privileges"
				elevate_privilege "dnf --nogpgcheck install -y ${REPO}/${PACKAGE}-${VERSION}.x86_64.rpm"
				;;
			*)
				whiptail --title "No packages available to download." --msgbox "Error." 8 78
				;;
		esac
		# Cleanup and finish
		rm $PACKAGE*.rpm
		# Done
		echo_message success "Installation of '$PACKAGE' complete."
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 78
		thirdparty
	else
		# Already installed
		echo_message success "$NAME already installed."
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 78
		thirdparty
	fi
}