#!/bin/bash

# Java
function install_oracle_java {
	# Variables
	PACKAGE=jre
	NAME="Oracle Java"
	VERSION="7u80"
	BUILD="b15"
	echo_message title "Starting $NAME installation..."
	# Check if package is installed
	if [ $(check_packages $PACKAGE; echo $?) = 1 ]; then
		# Install package(s)
		echo_message info "$NAME is not installed. Downloading remote package..."
		# Download RPM file that matches system architecture
		case `uname -i` in
			i386|i486|i586|i686)
				curl -jkLH "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/${VERSION}-${BUILD}/jre-${VERSION}-linux-i586.rpm > jre-${VERSION}-linux-i586.rpm
				;;
			x86_64)
				curl -jkLH "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/${VERSION}-${BUILD}/jre-${VERSION}-linux-x64.rpm > jre-${VERSION}-linux-x64.rpm
				;;
			*)
				whiptail --title "No packages available to download." --msgbox "Error." 8 56
				install_thirdparty
				;;
		esac
		# Install package(s)
		echo_message info "Installing $NAME..."
		echo_message warning "Requires root privileges"
		elevate_privilege "dnf --nogpgcheck install -y $PACKAGE*.rpm"
		# Cleanup and finish
		rm $PACKAGE*.rpm
		# Done
		echo_message success "Installation of '$PACKAGE' complete."
		whiptail --title "Finished" --msgbox "Installation of $NAME is complete." 8 56
		install_thirdparty
	else
		# Already installed
		echo_message success "$NAME already installed."
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 56
		install_thirdparty
	fi
}