#!/bin/bash

# RVM
function rvm {
	# Add key(s)
	echo_message info 'Adding key to keyring...'
	gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
	# Install
	echo_message info 'Installing RVM...'
	\curl -sSL https://get.rvm.io | bash -s stable --ruby
	# \curl -sSL https://get.rvm.io | bash # Uncomment for development version
	# Done
	echo_message success 'Done.'
	whiptail --title "Finished" --msgbox "Installation complete." 8 78
	thirdparty
}