#!/bin/bash

# Slack
function install_slack {
	# Variables
	PACKAGE=slack
	VERSION=3.0.5-0.1.fc21
	REPO=" https://downloads.slack-edge.com/linux_releases"
	NAME="Slack"
	# Install
	echo_message title "Starting $NAME installation..."
	# Check if package is installed
	if [ $(check_packages $PACKAGE; echo $?) = 1 ]; then
		# Install package(s)
		echo_message info "Installing $NAME..."
		# Install RPM file that matches system architecture
		case `uname -i` in
			i386|i486|i586|i686)
				whiptail --title  "No 32-bit packages are available to download." --msgbox "Error." 8 56
				install_thirdparty
				;;
			x86_64)
				echo_message warning "Requires root privileges"
				elevate_privilege "dnf --nogpgcheck install -y ${REPO}/${PACKAGE}-${VERSION}.x86_64.rpm"
				# Cleanup and finish
				rm $PACKAGE*.rpm
				;;
			*)
				whiptail --title "No packages available to download." --msgbox "Error." 8 56
				install_thirdparty
				;;
		esac
		# Finished
		echo_message success "Installation of '$PACKAGE' complete."
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 56
		install_thirdparty
	else
		# Already installed
		echo_message success "$NAME already installed."
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 56
		install_thirdparty
	fi
}