#!/bin/bash

# Slack
function slack {
	# Variables
	PACKAGE=slack
	VERSION=3.0.5-0.1.fc21
	REPO=" https://downloads.slack-edge.com/linux_releases"
	NAME="Slack"
	# Install
	echo_message header "Begin $NAME installation"
	# Check if package is installed
	check_packages $PACKAGE
	EXITSTATUS=$?
	# If package is not installed
	if [ $EXITSTATUS = 1 ]; then
		# Install package(s)
		echo_message info "Installing $NAME..."
		# Install RPM file that matches system architecture
		case `uname -i` in
			i386|i486|i586|i686)
				whiptail --title  "No 32-bit packages are available to download." --msgbox "Error." 8 78
				thirdparty
				;;
			x86_64)
				echo_message warning "Requires root privileges"
				elevate_privilege "dnf --nogpgcheck install -y ${REPO}/${PACKAGE}-${VERSION}.x86_64.rpm"
				# Cleanup and finish
				rm $PACKAGE*.rpm
				;;
			*)
				whiptail --title "No packages available to download." --msgbox "Error." 8 78
				thirdparty
				;;
		esac
		# Done
		echo_message success 'Done.'
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 78
		thirdparty
	else
		# Already installed
		echo_message success "$NAME already installed."
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 78
		thirdparty
	fi
}