#!/bin/bash

# Install Spotify
function install_spotify { 
	# Variables
	NAME="Spotify"
	PACKAGE="com.spotify.Client"
	REPO="https://flathub.org/repo/appstream"
	# Check if package is installed
	if [ $(check_flatpak $PACKAGE; echo $?) = 1 ]; then
		echo_message info "$NAME is not installed."
		# Install package(s)
		echo_message info "Installing $NAME flatpak..."
		flatpak install --from $REPO/$PACKAGE.flatpakref
		# Finished
		echo_message success "Installation of '$PACKAGE' complete."
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 56
		install_thirdparty
	else
		# Already installed
		echo_message success "$NAME already installed."
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 56
		install_thirdparty
	fi
}