#!/bin/bash

# Install Sublime Text
function download_sublime_text { 
	# Variables
	NAME="Sublime Text ($@)"
	PACKAGE=sublime-text
	KEY="https://download.sublimetext.com/sublimehq-rpm-pub.gpg"
	REPO="https://download.sublimetext.com/rpm/$@/x86_64/sublime-text.repo"
	# Check if package is installed
	if [ $(check_packages $PACKAGE; echo $?) = 1 ]; then
		echo_message info "$NAME is not installed."
		# Import signing key
		echo_message info "Importing $NAME signing key..."
		elevate_privilege "rpm -v --import $KEY"
		echo_message success "Key imported."
		# Add repository
		echo_message info "Adding $NAME repository..."
		elevate_privilege "dnf config-manager --add-repo $REPO"
		echo_message success "Repository added."
		# Install package(s)
		echo_message info "Installing '$PACKAGE'..."
		elevate_privilege "dnf install -y $PACKAGE"
		# Finished
		echo_message success "Installation of '$PACKAGE' complete."
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 56
		install_thirdparty
	else
		# Already installed
		echo_message success "$NAME already installed."
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 56
		install_thirdparty
	fi
}

# Install Sublime Text
function install_sublime_text {
	NAME="Sublime Text"
	# Install
	echo_message title "Starting $NAME installation..."
	VERSION=$(eval `resize` && whiptail \
		--title "$NAME" \
		--radiolist "Which version of $NAME would you like to install?" \
		--ok-button "Install" \
		--cancel-button "Go Back" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		"stable"	"Stable build" ON \
		"dev"		"Beta build" OFF \
		3>&1 1>&2 2>&3)
	# check exit status
	if [ $? = 0 ]; then
		case "${VERSION}" in
			stable)
				download_sublime_text stable
			;;
			dev)
				download_sublime_text dev
			;;
			*)
				install_thirdparty
			;;
		esac
	else
		# Cancelled
		echo_message info "Installation of $NAME cancelled."
		install_thirdparty
	fi
}