#!/bin/bash

# Install VLC
function install_vlc {
	# Variables
	PACKAGE=vlc
	NAME="VLC Media Player"
	echo_message title "Starting $NAME installation..."
	# Check if package is installed
	if [ $(check_packages $PACKAGE; echo $?) = 1 ]; then
		echo_message info "$NAME is not installed."
		# Add repository in this case RPM Fusion
		REPONAME="RPM Fusion (Free)"
		if (eval `resize` && whiptail \
			--title "Add $REPONAME Repository?" \
			--yesno "The $REPONAME repository is required to install $NAME.\n\nProceed with installation?" \
			10 60) then
			add_rpmfusion "free"
		else
			# Cancelled
			echo_message error "$REPONAME is required for $NAME installation. Aborting..."
			install_thirdparty
		fi
		# Install package(s)
		echo_message info "Installing '$PACKAGE'..."
		elevate_privilege "dnf install -y $PACKAGE"
		# Done
		echo_message success "Installation of '$PACKAGE' complete."
		whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 56
		install_thirdparty
	else
		# Already installed
		echo_message success "$NAME already installed."
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 56
		install_thirdparty
	fi
}