#!/bin/bash

# Install VLC
function vlc {
	# Variables
	PACKAGE=vlc
	NAME="VLC Media Player"
	# Install
	echo_message header "Begin $NAME installation"
	# Check if package is installed
	if [ $(check_packages $PACKAGE; echo $?) = 1 ]; then
		echo_message info "$NAME is not installed."
		# Add RPM Fusion
		REPOVERSION="free"
		if (eval `resize` && whiptail \
			--title "Add RPM Fusion ($REPOVERSION) Repository?" \
			--yesno "The RPM Fusion ($REPOVERSION) repository is required to install $NAME.\n\nProceed with installation?" \
			10 60) then
			# Add repository
			echo_message info 'Adding repository...'
			add_rpmfusion $REPOVERSION
		else
			thirdparty
		fi
		# Admin privileges
		elevate_privilege "dnf install -y $PACKAGE"
		# Done
		echo_message success "Installation of '$PACKAGE' complete."
		whiptail --title "Finished" --msgbox "Installation of $NAME is complete." 8 78
		thirdparty
	else
		# Already installed
		echo_message success "$NAME already installed."
		whiptail --title "Finished" --msgbox "$NAME is already installed." 8 78
		thirdparty
	fi
}