#!/bin/bash

# Install Fedora Restricted Extras
function rpmfusion {
if (whiptail --title "RPM Fusion" --yesno "Add RPM Fusion repository to software soruces?" 10 60) then
    # Check
    if [ -e /etc/yum.repos.d/rpmfusion-free.repo ]; then
        echo 'RPM Fusion is already in the repositories.'
        whiptail --msgbox "RPM Fusion is already in the repositories." 8 78
    else
        # Add repository
        echo 'Adding RPM Fusion to repositories...'
        show_info 'Requires root privileges:'
        su -c 'rpm -Uvh http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm'
        show_success 'Done.'
        # Update system
        echo 'Performing system update...'
        sudo dnf -y update
        echo 'Done'
        whiptail --title "Finished" --msgbox "RPM Fusion repository added." 8 78
    fi
    main
else
    clear && main
fi
}