#!/bin/bash

# Install Fedora Restricted Extras
function rpmfusion {
if (whiptail --title "RPM Fusion" --yesno "Add RPM Fusion repository to software soruces?" 10 60) then
    # Check
    if [ -e /etc/yum.repos.d/rpmfusion-free.repo ]; then
        clear
        echo 'RPM Fusion is already in the repositories.'
        echo ''
    else
        # Add repository
        echo 'Adding RPM Fusion to repositories...'
        show_info 'Requires root privileges:'
        su -c 'rpm -Uvh http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-stable.noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-stable.noarch.rpm'
        show_success 'Done.'
        # Update system
        echo 'Performing system update...'
        sudo dnf -y update
        echo 'Done'
    fi
    whiptail --title "Finished" --msgbox "RPM Fusion added." 8 78
    main
else
    clear && main
fi
}