#!/bin/bash

# libfprint
function install_libfprint_git {
	# Variables
	NAME="libfprint (git)"
	DEPS="fprintd fprintd-pam gcc-c++ libpam-fprintd libusb-devel libXv-devel nss nss-devel openssl-devel PackageKit-glib PackageKit-glib-devel pixman pixman-devel xv"
	REPO="https://github.com/3v1n0/libfprint"
	# Clone from source repository
	echo_message info "Cloning $NAME from '$REPO'..."
	# git clone
	git clone $REPO
	# build from source
	echo_message info "Building $NAME from source..."
	# compile
	echo_message info "Compiling..."
	cd libfprint
	./autogen.sh
	make
	# install
	echo_message info "Installing $NAME..."
	elevate_privilege "make install"
	# make Fedora specific fixes.
	echo_message info "Making some necessary Fedora-specific post-installation fixes..."
	# make some symlinks
	elevate_privilege "ln -s /usr/local/lib/libfprint.a /usr/lib64/libfprint.a"
	elevate_privilege "ln -s /usr/local/lib/libfprint.la /usr/lib64/libfprint.la"
	elevate_privilege "ln -s /usr/local/lib/libfprint.so /usr/lib64/libfprint.so"
	elevate_privilege "ln -s /usr/local/lib/libfprint.so.0 /usr/lib64/libfprint.so.0"
	elevate_privilege "ln -s /usr/local/lib/libfprint.so.0.0.0 /usr/lib64/libfprint.so.0.0.0"
	elevate_privilege "ln -s /usr/local/lib/pkgconfig/libfprint.pc /usr/lib64/pkgconfig/libfprint.pc"
	# allow fingerprint authentication on gnome login/lock screen
	elevate_privilege "sed -i '1s/^/auth        sufficient    pam_fprintd.so\n/' /etc/pam.d/gdm-fingerprint"
	# enable fingerprint authentication
	elevate_privilege "authconfig --enablefingerprint --update"
	# to enroll fingers, run:
	# for finger in {left,right}-{thumb,{index,middle,ring,little}-finger}; do fprintd-enroll -f "$finger" "$USER"; done
	# Finished
	echo_message success "Installation of '$PACKAGE' complete."
	whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 56
	install_from_source
}